
export const ERR_AUTH = 'Bạn hiện chưa đăng nhập, vui lòng đăng nhập để tiếp tục'
export const INTERNAL_SERVER_ERROR = 'Server đang update hoặc mất kết nối, vui lòng thử lại sau.'

export const NOT_YET_USERNAME = 'Vui lòng nhập username'
export const NOT_YET_EMAIL = 'Vui lòng nhập email'
export const NOT_YET_PASSWORD = 'Vui lòng nhập mật khẩu'
export const ERR_VAL_PASSWORD = 'Vui lòng nhập mật khẩu đúng định dạng'
export const ERR_CONFIRM_PASSWORD = 'Mật khẩu nhập lại không chính xác'
export const NOT_YET_STORYNAME = 'Vui lòng nhập tên truyện'
export const NOT_YET_STORYTYPE = 'Vui lòng chọn loại truyện'
export const NOT_YET_CATEGORY = 'Vui lòng chọn danh mục'
export const NOT_YET_AVATAR = 'Vui lòng chọn ảnh đại diện'
export const ERR_FILE_IMAGE = 'File ảnh không đúng định dạng'
export const ERR_FILE_UPLOAD = 'File ảnh vượt quá 5 mb'
export const ERR_VALID_EMAIL = 'Email không đúng định dạng'
export const ERR_DEPOSIT_MONEY = 'Số tiền cần lớn hơn 0'


export const ACTION_CREATE_SUCCESS = 'Thêm mới thành công!'
export const ACTION_UPDATE_SUCCESS = 'Cập nhật thành công!'
export const ACTION_DELETE_SUCCESS = 'Xoá thành công!'
export const ACTION_REGISTER_CONTINUE = 'Nhập mã xác thực qua email để tiếp tục'
export const ACTION_REGISTER_SUCCESS = 'Đăng ký thành công'
export const ACTION_LOGIN_SUCCESS = 'Đăng nhập thành công'
export const ACTION_BUY_CHAPTER_SUCCESS = 'Mua chương thành công'
export const ACTION_DEPOSIT_SUCCESS = 'Nạp tiền thành công '